# Generated by Django 5.1.2 on 2024-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('key', models.CharField(max_length=6, unique=True, verbose_name='key')),
            ],
            options={
                'verbose_name': 'Created Link',
                'verbose_name_plural': 'Created Links',
            },
        ),
    ]
